name: "Semantic Pull Request"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    branches:
      - main

jobs:
  semantic-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # v5
        env:
          GITHUB_TOKEN: {% raw %}${{ secrets.GITHUB_TOKEN }}{% endraw %}