name: typos

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  CLICOLOR: 1

jobs:
  typos:
    name: typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - name: Spell Check Repo
        uses: crate-ci/typos@0f0ccba9ed1df83948f0c15026e4f5ccfce46109 # v1.32.0
