name: typos

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  CLICOLOR: 1

jobs:
  typos:
    name: typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: Spell Check Repo
        uses: crate-ci/typos@d43b6c087ac471e2ea7b8af622ff15f05c0c365b # v1.50.1
