# .github/workflows/ci-base.yml
name: CI Base

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      args:
        required: true
        type: string

jobs:
  run-uv:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ inputs.name }}-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.4"
          enable-cache: true
      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run ${{ inputs.name }}
        run: uv run ${{ inputs.args }}