name: 🔐 CI Base

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      args:
        required: true
        type: string

jobs:
  run-uv:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: ${{ inputs.name }}-${{ github.ref_name }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install uv
        uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca # v6
        with:
          version: "0.7.4"
          enable-cache: true
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run ${{ inputs.name }}
        run: uv run ${{ inputs.args }}