name: deptry

on: pull_request

jobs:
  deptry:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: deptry-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.4"
          enable-cache: true

      - name: Install the project
        run: uv sync --locked --all-extras --dev
      - name: Run deptry
        run: uv run deptry .
