name: typos

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

env:
  CLICOLOR: 1

jobs:
  typos:
    name: typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: Spell Check Repo
        uses: crate-ci/typos@v1.32.0
